services:
  - type: web
    name: gfm-backend
    env: node
    region: virginia
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && node dist/src/main.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: postgresql://postgres:SvtTzYwUrtxwxAYb@db.cweuhfocjznrbxrqdgjx.supabase.co:5432/postgres?schema=public
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h


