services:
  - type: web
    name: gfm-backend
    env: node
    region: virginia
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && node dist/src/main.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_jJxuq6CibNQ0@ep-wandering-frog-aw7wigkj.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h

  - type: web
    name: gfm-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://gfm-backend.onrender.com

